### PR TITLE
Added CSS Modules with auto prefixer 

### PR DESCRIPTION
**Pull request by Epenance**
Hi there,

I've included the use of CSS modules with SCSS into the project as its something i use on every single project it made sense it was a part of this too.

Ive also added a small example to the Counter component by including the styles from Counter.scss

Additionally i also added a auto prefixer which currently prefixes back for the last 2 versions of the browsers to make sure it all looks awesome.

Hope you can use it.

### CODE REVIEW

**Comment by tsaiDavid** [comment]
@Epenance - thanks! It looks great - was wondering what the `.idea` file was, mentioned in the .gitignore? Also - would you say CSS Modules are probably the most popular package used for handling CSS/SCSS? Thanks for your work!

**Comment by blairanderson** [comment]
@tsaiDavid the `.idea` in gitignore is from rubymine and webstorm editor/IDE. they automatically create an idea folder with a bunch of metadata about the project.

**Comment by rygine** [comment]
FYI, the `autoprefixer-loader` is deprecated in favor of the `postcss-loader`

**Comment by tsaiDavid** [comment]
Gotcha, good looking out - looks like we might want to use postcss-loader?

**Comment by tsaiDavid** [comment]
@Epenance, @rygine, @blairanderson - thanks for bringing this to my attention and definitely thanks for the effort, certainly don't want to add something that will/is deprecated! Let's revisit this? Would love your suggestions on moving forward.

**Pull request closed without merging**
